version: "3"

services:
  etracs-server:
    container_name: etracs-server
    image: ramesesinc/etracs-server-municipality:2.5.03.02.01
    restart: always
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: 10m
    environment:
      TZ: "Asia/Manila"
    env_file:
      - ./env.conf
      - ../../_res/env.conf
      - ../../_custom/env.conf
    ports:
      - "8060:8060"
      - "8061:8061"
      - "8070:8070"
    volumes:
      - ./modules:/apps/etracs25/modules

      - ../../_custom/datasources:/services/datasources
      - ../../_res/connections:/apps/etracs25/connections/ext
      - ../../_custom/module-server:/apps/etracs25/modules/ext/zzz-lgu-custom-module

      - ../../_custom/output:/apps/server/output
      - ../../_custom/fileserver:/fileserver
