version: "3"

services:

  epayment-server:
    container_name: epayment-server
    image: ramesesinc/local-epayment-server:2.5.01.02.04
    restart: always
    logging: 
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "10m"
    environment:
      TZ: "Asia/Manila"
    env_file:
      - ./env.conf
      - ../../_res/env.conf
      - ../../_custom/env.conf
    ports: 
      - "8095:8070"
    volumes:
      - ../../_res/connections:/enterprise/connections/ext
      - ../../_custom/datasources/epaymentds:/services/datasources/mainds

      - ./module-client/reports:/apps/server/templates
      - ../../_custom/module-client/epayment:/apps/server/templates/custom
      - ../../_custom/output:/apps/server/output
