version: "3"

services:

  download-nginx-server:
    container_name: download-nginx-server
    image: nginx:latest
    restart: always
    logging:
      driver: "json-file"
      options: 
        max-file: "5"
        max-size: 10m
    environment:
      TZ: "Asia/Manila"
    env_file:
      - ../../_custom/env.conf
    ports:
      - "8000:80"
      - "80:80"
    volumes:
      - ./nginx/_src:/_src
      - ./nginx/_src/conf.d:/etc/nginx/conf.d
      - ./nginx/resources:/www

      - ../../_custom/static_files:/www/static_files

    command: ["sh", "/_src/scripts/run.sh" ]


  download-node-server:
    container_name: download-node-server
    image: ramesesinc/node-download-server:0.0.3
    restart: always
    logging:
      driver: "json-file"
      options: 
        max-file: "5"
        max-size: 10m
    environment:
      TZ: "Asia/Manila"
    env_file:
      - ../../_res/env.conf
      - ../../_custom/env.conf 
    ports:
      - "8001:8000"
    volumes:
      - ./node/resources:/apps/server/public/resources
      - ../../_res/env.conf:/apps/server/public/resources/res.conf

      - ../../_custom/env.conf:/apps/server/public/resources/custom.conf
      - ../../_custom/module-client:/apps/server/public/resources/downloads/modules/custom

      - ../../appserver/epayment/module-client:/apps/server/public/resources/downloads/modules/epayment
