version: "3"

services:

  mail-primary: 
    image: ramesesinc/mail-server:latest
    container_name: mail-primary
    restart: always
    logging: 
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "10m"
    env_file:
      - ./env.conf
      - ../_custom/env.conf
    ports:
      - "26:25"
