version: "3"

services:
  
  rameses-notification-server:
    image: ramesesinc/notification-server:1.0
    container_name: rameses-notification-server
    restart: always
    logging:
      driver: "json-file"
      options: 
        max-file: "5"
        max-size: 10m
    environment:
      TZ: "Asia/Manila"
    env_file:
      - ./env.conf
    ports: 
      - "7080:8080"
